name: main

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-env name=FILELIST::$(printf '"%s" ' **.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: guest-faq.md ./show-specifics/dotnetcore.md ./show-specifics/wafflingtaylors.md --pdf-engine=xelatex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -o guest-faq.pdf --toc
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: ./guest-faq.pdf